# cargo-deny configuration
# https://embarkstudios.github.io/cargo-deny/

[graph]
# Exclude dev dependencies from the graph
all-features = false
no-default-features = false

[licenses]
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "Unlicense",
    "CC0-1.0",
    "0BSD",
    "BUSL-1.1",
    "LGPL-3.0",
    "Zlib",
    "MPL-2.0",
]

# List of explicitly disallowed licenses  
# Note: 'deny' has been replaced with 'exceptions' for specific license handling

# Confidence threshold for detecting a license from a license text
confidence-threshold = 0.8

# Allow 1 or more license expressions to be ignored
exceptions = []

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"

# Lint level for when a crate version requirement is `*`
wildcards = "allow"

# The graph highlights used to determine which versions of a crate to
# consider for the multiple-versions lint
highlight = "all"

# List of crates that are allowed
allow = []

# List of crates to deny
deny = [
    # { name = "openssl", version = "*" },
]

# List of features to skip checking
skip = []

# List of crates which are allowed to have duplicates
skip-tree = []

[advisories]
# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"

# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]

# The scope for unmaintained crates checking
unmaintained = "workspace"

# The lint level for crates that have been yanked from their source registry
yanked = "warn"

# A list of advisory IDs to ignore
ignore = [
    # Ignore specific advisories here if needed
    # "RUSTSEC-2020-0001",
]

[sources]
# Lint level for what to happen when a crate from a crate registry that is
# not in the allow list is encountered
unknown-registry = "warn"

# Lint level for what to happen when a crate from a git repository that is not
# in the allow list is encountered
unknown-git = "warn"

# List of URLs for allowed crate registries
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

# List of URLs for allowed Git repositories
allow-git = [
    "https://github.com/risc0/risc0-ethereum",
] 