services:
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: notsecurepassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
