services:
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=notsecurepassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9095:9090"

  grafana:
    image: grafana/grafana-oss
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3001:3000"
