[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
blob-verification-methods = { workspace = true }
proof-equivalence-methods = { workspace = true }
risc0-steel = { workspace = true, features = ["host"] }
risc0-zkvm = { workspace = true, features = ["client"] }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
tokio-postgres = { workspace = true }
ethabi = { workspace = true }
hex = {workspace = true}
chrono = {workspace = true}
rust-kzg-bn254-prover = { workspace = true }
ark-bn254 = {workspace = true}
num-bigint = {workspace = true}
rust-kzg-bn254-primitives = {workspace = true}
tonic = {workspace = true}
kzgpad-rs = {workspace = true}
prost = {workspace = true}
common = {workspace = true}
secrecy = {workspace = true}
alloy = {workspace = true}
tiny-keccak = { version = "2.0", features = ["keccak"] }
