[package]
name = "methods"
description = "This contains the guest program that is compiled to run inside the zkvm"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { workspace = true }

[package.metadata.risc0]
methods = ["guest"]

