[profile.default]
src = "src"
out = "out"
libs = ["../lib"]

remappings = [
    "risc0-ethereum/=../lib/risc0-ethereum/contracts/src/",
    "openzeppelin/=../lib/risc0-ethereum/lib/openzeppelin-contracts/",
    "forge-std/=../lib/forge-std/src/"
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
