name: Contracts CI

on:
  push:
    branches: [ main ]
    paths: 
      - 'contracts/**'
      - 'lib/**'
      - '.github/workflows/contracts.yml'
  pull_request:
    branches: [ main ]
    paths: 
      - 'contracts/**'
      - 'lib/**'
      - '.github/workflows/contracts.yml'

jobs:
  foundry:
    name: Foundry Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@e499156d7d918eb5c652fdf7cb8b1023a17a67bf # v1.2.0

      - name: Install dependencies
        working-directory: contracts
        run: forge install

      - name: Check formatting
        working-directory: contracts
        run: forge fmt --check

      - name: Build contracts
        working-directory: contracts
        run: forge build

      - name: Run tests
        working-directory: contracts
        run: forge test -vvv

      - name: Upload contract artifacts
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.5
        with:
          name: contract-artifacts
          path: |
            contracts/out/**/*.json
          retention-days: 7

  slither:
    name: Slither Analysis
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@e499156d7d918eb5c652fdf7cb8b1023a17a67bf # v1.2.0  

      - name: Install dependencies
        working-directory: contracts
        run: forge install

      - name: Build contracts
        working-directory: contracts
        run: forge build

      - name: Run Slither
        uses: crytic/slither-action@4fd765aeef19915d04ddf0be90c2930036a774d8 # v0.4.1
        with:
          working-directory: contracts
          target: src/
          slither-config: slither.config.json
          fail-on: none
        continue-on-error: true 